import re
import json

new_resources = [
    # Web Dev (50)
    {"title": "React", "desc": "A declarative, efficient, and flexible JavaScript library for building user interfaces.", "cat": "Web Dev", "link": "https://github.com/facebook/react"},
    {"title": "Vue.js", "desc": "Vue.js is a progressive, incrementally-adoptable JavaScript framework for building UI on the web.", "cat": "Web Dev", "link": "https://github.com/vuejs/core"},
    {"title": "Angular", "desc": "The modern web developer's platform.", "cat": "Web Dev", "link": "https://github.com/angular/angular"},
    {"title": "Next.js", "desc": "The React Framework", "cat": "Web Dev", "link": "https://github.com/vercel/next.js"},
    {"title": "Nuxt", "desc": "The Intuitive Vue Framework.", "cat": "Web Dev", "link": "https://github.com/nuxt/nuxt"},
    {"title": "Svelte", "desc": "Cybernetically enhanced web apps", "cat": "Web Dev", "link": "https://github.com/sveltejs/svelte"},
    {"title": "Tailwind CSS", "desc": "A utility-first CSS framework for rapid UI development.", "cat": "Web Dev", "link": "https://github.com/tailwindlabs/tailwindcss"},
    {"title": "Bootstrap", "desc": "The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.", "cat": "Web Dev", "link": "https://github.com/twbs/bootstrap"},
    {"title": "Node.js", "desc": "Node.js JavaScript runtime", "cat": "Web Dev", "link": "https://github.com/nodejs/node"},
    {"title": "Express", "desc": "Fast, unopinionated, minimalist web framework for node.", "cat": "Web Dev", "link": "https://github.com/expressjs/express"},
    {"title": "Django", "desc": "The Web framework for perfectionists with deadlines.", "cat": "Web Dev", "link": "https://github.com/django/django"},
    {"title": "Flask", "desc": "The Python micro framework for building web applications.", "cat": "Web Dev", "link": "https://github.com/pallets/flask"},
    {"title": "FastAPI", "desc": "FastAPI framework, high performance, easy to learn, fast to code, ready for production", "cat": "Web Dev", "link": "https://github.com/tiangolo/fastapi"},
    {"title": "Laravel", "desc": "A PHP framework for web artisans", "cat": "Web Dev", "link": "https://github.com/laravel/laravel"},
    {"title": "Ruby on Rails", "desc": "Ruby on Rails", "cat": "Web Dev", "link": "https://github.com/rails/rails"},
    {"title": "Spring Boot", "desc": "Spring Boot", "cat": "Web Dev", "link": "https://github.com/spring-projects/spring-boot"},
    {"title": "Deno", "desc": "A modern runtime for JavaScript and TypeScript.", "cat": "Web Dev", "link": "https://github.com/denoland/deno"},
    {"title": "NestJS", "desc": "A progressive Node.js framework for building efficient, scalable, and enterprise-grade server-side applications", "cat": "Web Dev", "link": "https://github.com/nestjs/nest"},
    {"title": "Strapi", "desc": "The leading open-source headless CMS. It’s 100% JavaScript and fully customizable.", "cat": "Web Dev", "link": "https://github.com/strapi/strapi"},
    {"title": "Supabase", "desc": "The open source Firebase alternative.", "cat": "Web Dev", "link": "https://github.com/supabase/supabase"},
    {"title": "Prisma", "desc": "Next-generation ORM for Node.js & TypeScript | PostgreSQL, MySQL, MariaDB, SQL Server, SQLite, MongoDB and CockroachDB", "cat": "Web Dev", "link": "https://github.com/prisma/prisma"},
    {"title": "Vite", "desc": "Next generation frontend tooling. It's fast!", "cat": "Web Dev", "link": "https://github.com/vitejs/vite"},
    {"title": "Webpack", "desc": "A bundler for javascript and friends.", "cat": "Web Dev", "link": "https://github.com/webpack/webpack"},
    {"title": "Babel", "desc": "Babel is a compiler for writing next generation JavaScript.", "cat": "Web Dev", "link": "https://github.com/babel/babel"},
    {"title": "Storybook", "desc": "Storybook is a frontend workshop for building UI components and pages in isolation.", "cat": "Web Dev", "link": "https://github.com/storybookjs/storybook"},
    {"title": "Redux", "desc": "Predictable state container for JavaScript apps", "cat": "Web Dev", "link": "https://github.com/reduxjs/redux"},
    {"title": "Zustand", "desc": "Bear necessities for state management in React", "cat": "Web Dev", "link": "https://github.com/pmndrs/zustand"},
    {"title": "GraphQL", "desc": "GraphQL is a query language and execution engine tied to any backend service.", "cat": "Web Dev", "link": "https://github.com/graphql/graphql-spec"},
    {"title": "Apollo Client", "desc": "A fully-featured, production ready caching GraphQL client for every UI framework and GraphQL server.", "cat": "Web Dev", "link": "https://github.com/apollographql/apollo-client"},
    {"title": "tRPC", "desc": "End-to-end typesafe APIs made easy", "cat": "Web Dev", "link": "https://github.com/trpc/trpc"},
    {"title": "Gatsby", "desc": "The fastest frontend for the headless web.", "cat": "Web Dev", "link": "https://github.com/gatsbyjs/gatsby"},
    {"title": "Astro", "desc": "The web framework for content-driven websites.", "cat": "Web Dev", "link": "https://github.com/withastro/astro"},
    {"title": "Qwik", "desc": "The HTML-first framework. Instant apps of any size with ~ 1kb JS", "cat": "Web Dev", "link": "https://github.com/BuilderIO/qwik"},
    {"title": "SolidJS", "desc": "A declarative, efficient, and flexible JavaScript library for building user interfaces.", "cat": "Web Dev", "link": "https://github.com/solidjs/solid"},
    {"title": "Three.js", "desc": "JavaScript 3D Library.", "cat": "Web Dev", "link": "https://github.com/mrdoob/three.js"},
    {"title": "ECharts", "desc": "Apache ECharts is a powerful, interactive charting and data visualization library for browser", "cat": "Web Dev", "link": "https://github.com/apache/echarts"},
    {"title": "Chart.js", "desc": "Simple HTML5 Charts using the <canvas> tag", "cat": "Web Dev", "link": "https://github.com/chartjs/Chart.js"},
    {"title": "Ant Design", "desc": "An enterprise-class UI design language and React UI library", "cat": "Web Dev", "link": "https://github.com/ant-design/ant-design"},
    {"title": "MUI", "desc": "MUI Core: Ready-to-use foundational React components, free forever.", "cat": "Web Dev", "link": "https://github.com/mui/material-ui"},
    {"title": "Chakra UI", "desc": "Simple, Modular & Accessible UI Components for your React Applications", "cat": "Web Dev", "link": "https://github.com/chakra-ui/chakra-ui"},
    {"title": "DaisyUI", "desc": "The most popular component library for Tailwind CSS", "cat": "Web Dev", "link": "https://github.com/saadeghi/daisyui"},
    {"title": "Framer Motion", "desc": "Open source, production-ready animation and gesture library for React", "cat": "Web Dev", "link": "https://github.com/framer/motion"},
    {"title": "HTMX", "desc": "</> htmx - high power tools for HTML", "cat": "Web Dev", "link": "https://github.com/bigskysoftware/htmx"},
    {"title": "jQuery", "desc": "jQuery JavaScript Library", "cat": "Web Dev", "link": "https://github.com/jquery/jquery"},
    {"title": "Alpine.js", "desc": "A rugged, minimal framework for composing JavaScript behavior in your markup.", "cat": "Web Dev", "link": "https://github.com/alpinejs/alpine"},
    {"title": "Playwright", "desc": "Playwright is a framework for Web Testing and Automation.", "cat": "Web Dev", "link": "https://github.com/microsoft/playwright"},
    {"title": "Puppeteer", "desc": "Headless Chrome Node.js API", "cat": "Web Dev", "link": "https://github.com/puppeteer/puppeteer"},
    {"title": "Cypress", "desc": "Fast, easy and reliable testing for anything that runs in a browser.", "cat": "Web Dev", "link": "https://github.com/cypress-io/cypress"},
    {"title": "Jest", "desc": "Delightful JavaScript Testing.", "cat": "Web Dev", "link": "https://github.com/jestjs/jest"},
    {"title": "Vitest", "desc": "Next generation testing framework powered by Vite.", "cat": "Web Dev", "link": "https://github.com/vitest-dev/vitest"},

    # AI / ML (40)
    {"title": "TensorFlow", "desc": "An Open Source Machine Learning Framework for Everyone", "cat": "AI/ML", "link": "https://github.com/tensorflow/tensorflow"},
    {"title": "PyTorch", "desc": "Tensors and Dynamic neural networks in Python with strong GPU acceleration", "cat": "AI/ML", "link": "https://github.com/pytorch/pytorch"},
    {"title": "Keras", "desc": "Deep Learning for humans", "cat": "AI/ML", "link": "https://github.com/keras-team/keras"},
    {"title": "Scikit-Learn", "desc": "Machine learning in Python", "cat": "AI/ML", "link": "https://github.com/scikit-learn/scikit-learn"},
    {"title": "Hugging Face Transformers", "desc": "State-of-the-art Machine Learning for Pytorch, TensorFlow, and JAX.", "cat": "AI/ML", "link": "https://github.com/huggingface/transformers"},
    {"title": "LangChain", "desc": "Building applications with LLMs through composability", "cat": "AI/ML", "link": "https://github.com/langchain-ai/langchain"},
    {"title": "AutoGPT", "desc": "An experimental open-source attempt to make GPT-4 fully autonomous.", "cat": "AI/ML", "link": "https://github.com/Significant-Gravitas/AutoGPT"},
    {"title": "Stable Diffusion WebUI", "desc": "Stable Diffusion web UI", "cat": "AI/ML", "link": "https://github.com/AUTOMATIC1111/stable-diffusion-webui"},
    {"title": "OpenCV", "desc": "Open Source Computer Vision Library", "cat": "AI/ML", "link": "https://github.com/opencv/opencv"},
    {"title": "YOLOv5", "desc": "YOLOv5 in PyTorch > ONNX > CoreML > TFLite", "cat": "AI/ML", "link": "https://github.com/ultralytics/yolov5"},
    {"title": "YOLOv8", "desc": "Ultralytics YOLOv8", "cat": "AI/ML", "link": "https://github.com/ultralytics/ultralytics"},
    {"title": "DeepSpeed", "desc": "DeepSpeed is a deep learning optimization library that makes distributed training easy", "cat": "AI/ML", "link": "https://github.com/microsoft/DeepSpeed"},
    {"title": "Ray", "desc": "Ray is a unified framework for scaling AI and Python applications.", "cat": "AI/ML", "link": "https://github.com/ray-project/ray"},
    {"title": "Gradio", "desc": "Create UIs for your machine learning model in Python in 3 minutes", "cat": "AI/ML", "link": "https://github.com/gradio-app/gradio"},
    {"title": "Streamlit", "desc": "Streamlit — The fastest way to build data apps in Python", "cat": "AI/ML", "link": "https://github.com/streamlit/streamlit"},
    {"title": "XGBoost", "desc": "Scalable, Portable and Distributed Gradient Boosting (GBDT, GBRT or GBM) Library", "cat": "AI/ML", "link": "https://github.com/dmlc/xgboost"},
    {"title": "LightGBM", "desc": "A fast, distributed, high performance gradient boosting framework", "cat": "AI/ML", "link": "https://github.com/microsoft/LightGBM"},
    {"title": "Pandas", "desc": "Flexible and powerful data analysis / manipulation library for Python", "cat": "AI/ML", "link": "https://github.com/pandas-dev/pandas"},
    {"title": "NumPy", "desc": "The fundamental package for scientific computing with Python.", "cat": "AI/ML", "link": "https://github.com/numpy/numpy"},
    {"title": "Matplotlib", "desc": "Matplotlib: plotting with Python", "cat": "AI/ML", "link": "https://github.com/matplotlib/matplotlib"},
    {"title": "Seaborn", "desc": "Statistical data visualization in Python", "cat": "AI/ML", "link": "https://github.com/mwaskom/seaborn"},
    {"title": "NLTK", "desc": "Natural Language Toolkit", "cat": "AI/ML", "link": "https://github.com/nltk/nltk"},
    {"title": "SpaCy", "desc": "Industrial-strength Natural Language Processing (NLP) in Python", "cat": "AI/ML", "link": "https://github.com/explosion/spaCy"},
    {"title": "Diffusers", "desc": "Diffusers: State-of-the-art diffusion models for image and audio generation in PyTorch.", "cat": "AI/ML", "link": "https://github.com/huggingface/diffusers"},
    {"title": "LlamaIndex", "desc": "LlamaIndex (GPT Index) is a data framework for your LLM applications", "cat": "AI/ML", "link": "https://github.com/run-llama/llama_index"},
    {"title": "Ollama", "desc": "Get up and running with Llama 3, Mistral, Gemma, and other large language models.", "cat": "AI/ML", "link": "https://github.com/ollama/ollama"},
    {"title": "LocalAI", "desc": "Free, Open Source OpenAI alternative.", "cat": "AI/ML", "link": "https://github.com/mudler/LocalAI"},
    {"title": "Chroma", "desc": "The AI-native open-source embedding database", "cat": "AI/ML", "link": "https://github.com/chroma-core/chroma"},
    {"title": "Milvus", "desc": "A cloud-native vector database, storage for next generation AI applications", "cat": "AI/ML", "link": "https://github.com/milvus-io/milvus"},
    {"title": "Qdrant", "desc": "Qdrant - Vector Database for the next generation of AI applications.", "cat": "AI/ML", "link": "https://github.com/qdrant/qdrant"},
    {"title": "Faiss", "desc": "A library for efficient similarity search and clustering of dense vectors.", "cat": "AI/ML", "link": "https://github.com/facebookresearch/faiss"},
    {"title": "Gymnasium", "desc": "An API standard for single-agent reinforcement learning environments", "cat": "AI/ML", "link": "https://github.com/Farama-Foundation/Gymnasium"},
    {"title": "MLflow", "desc": "Open source platform for the machine learning lifecycle", "cat": "AI/ML", "link": "https://github.com/mlflow/mlflow"},
    {"title": "Weights & Biases", "desc": "A tool for machine learning experiment tracking, dataset versioning, and project collaboration.", "cat": "AI/ML", "link": "https://github.com/wandb/wandb"},
    {"title": "ONNX", "desc": "Open Neural Network Exchange", "cat": "AI/ML", "link": "https://github.com/onnx/onnx"},
    {"title": "TensorRT", "desc": "NVIDIA TensorRT is a C++ library for high performance inference on NVIDIA GPUs", "cat": "AI/ML", "link": "https://github.com/NVIDIA/TensorRT"},
    {"title": "vLLM", "desc": "A high-throughput and memory-efficient LLM inference and serving engine", "cat": "AI/ML", "link": "https://github.com/vllm-project/vllm"},
    {"title": "Jupyter", "desc": "Jupyter Notebook", "cat": "AI/ML", "link": "https://github.com/jupyter/notebook"},
    {"title": "ColossalAI", "desc": "Making large AI models cheaper, faster, and more accessible", "cat": "AI/ML", "link": "https://github.com/hpcaitech/ColossalAI"},
    {"title": "Whisper", "desc": "Robust Speech Recognition via Large-Scale Weak Supervision", "cat": "AI/ML", "link": "https://github.com/openai/whisper"},

    # Cybersecurity (30)
    {"title": "Metasploit", "desc": "Metasploit Framework", "cat": "Cybersecurity", "link": "https://github.com/rapid7/metasploit-framework"},
    {"title": "Nmap", "desc": "Nmap - the Network Mapper.", "cat": "Cybersecurity", "link": "https://github.com/nmap/nmap"},
    {"title": "Wireshark", "desc": "Wireshark is the world's most popular network protocol analyzer.", "cat": "Cybersecurity", "link": "https://github.com/wireshark/wireshark"},
    {"title": "Sqlmap", "desc": "Automatic SQL injection and database takeover tool", "cat": "Cybersecurity", "link": "https://github.com/sqlmapproject/sqlmap"},
    {"title": "Radare2", "desc": "UNIX-like reverse engineering framework and command-line toolset", "cat": "Cybersecurity", "link": "https://github.com/radareorg/radare2"},
    {"title": "Ghidra", "desc": "Ghidra is a software reverse engineering (SRE) framework", "cat": "Cybersecurity", "link": "https://github.com/NationalSecurityAgency/ghidra"},
    {"title": "Aircrack-ng", "desc": "WiFi security auditing tools suite", "cat": "Cybersecurity", "link": "https://github.com/aircrack-ng/aircrack-ng"},
    {"title": "BloodHound", "desc": "Six Degrees of Domain Admin", "cat": "Cybersecurity", "link": "https://github.com/BloodHoundAD/BloodHound"},
    {"title": "Hashcat", "desc": "World's fastest and most advanced password recovery utility", "cat": "Cybersecurity", "link": "https://github.com/hashcat/hashcat"},
    {"title": "John the Ripper", "desc": "John the Ripper jumbo - advanced offline password cracker", "cat": "Cybersecurity", "link": "https://github.com/openwall/john"},
    {"title": "Burp Suite Free/Pro Extensions", "desc": "Various extensions for Burp Suite", "cat": "Cybersecurity", "link": "https://github.com/PortSwigger/bapps"},
    {"title": "ZAP", "desc": "The OWASP ZAP core project", "cat": "Cybersecurity", "link": "https://github.com/zaproxy/zaproxy"},
    {"title": "Nuclei", "desc": "Fast and customizable vulnerability scanner based on simple YAML based DSL.", "cat": "Cybersecurity", "link": "https://github.com/projectdiscovery/nuclei"},
    {"title": "FFuF", "desc": "Fast web fuzzer written in Go", "cat": "Cybersecurity", "link": "https://github.com/ffuf/ffuf"},
    {"title": "Gobuster", "desc": "Directory/File, DNS and VHost busting tool written in Go", "cat": "Cybersecurity", "link": "https://github.com/OJ/gobuster"},
    {"title": "Amass", "desc": "In-depth Attack Surface Mapping and Asset Discovery", "cat": "Cybersecurity", "link": "https://github.com/owasp-amass/amass"},
    {"title": "Sublist3r", "desc": "Fast subdomains enumeration tool for penetration testers", "cat": "Cybersecurity", "link": "https://github.com/aboul3la/Sublist3r"},
    {"title": "WpScan", "desc": "WPScan is a free, for non-commercial use, black box WordPress vulnerability scanner", "cat": "Cybersecurity", "link": "https://github.com/wpscanteam/wpscan"},
    {"title": "Responder", "desc": "Responder is a LLMNR, NBT-NS and MDNS poisoner", "cat": "Cybersecurity", "link": "https://github.com/SpiderLabs/Responder"},
    {"title": "Empire", "desc": "Empire is a PowerShell and Python post-exploitation agent.", "cat": "Cybersecurity", "link": "https://github.com/BC-SECURITY/Empire"},
    {"title": "Cobalt Strike Community Kit", "desc": "Community kit for Cobalt Strike", "cat": "Cybersecurity", "link": "https://github.com/Cobalt-Strike/community_kit"},
    {"title": "Sliver", "desc": "Adversary Emulation Framework", "cat": "Cybersecurity", "link": "https://github.com/BishopFox/sliver"},
    {"title": "Mythic", "desc": "A collaborative, multi-platform, cross-architecture, command and control framework.", "cat": "Cybersecurity", "link": "https://github.com/its-a-feature/Mythic"},
    {"title": "Impacket", "desc": "Impacket is a collection of Python classes for working with network protocols.", "cat": "Cybersecurity", "link": "https://github.com/fortra/impacket"},
    {"title": "Dirsearch", "desc": "Web path scanner", "cat": "Cybersecurity", "link": "https://github.com/maurosoria/dirsearch"},
    {"title": "TruffleHog", "desc": "Find and verify credentials", "cat": "Cybersecurity", "link": "https://github.com/trufflesecurity/trufflehog"},
    {"title": "Gitleaks", "desc": "Scan git repos (or files) for secrets using regex and entropy", "cat": "Cybersecurity", "link": "https://github.com/zricethezav/gitleaks"},
    {"title": "Semgrep", "desc": "Lightweight static analysis for many languages", "cat": "Cybersecurity", "link": "https://github.com/returntocorp/semgrep"},
    {"title": "Wazuh", "desc": "Wazuh - The Open Source Security Platform", "cat": "Cybersecurity", "link": "https://github.com/wazuh/wazuh"},
    {"title": "Suricata", "desc": "Suricata is a network Intrusion Detection System, Intrusion Prevention System and Network Security Monitoring engine.", "cat": "Cybersecurity", "link": "https://github.com/OISF/suricata"},

    # Mobile (30)
    {"title": "Flutter", "desc": "Flutter makes it easy and fast to build beautiful apps for mobile and beyond", "cat": "Mobile", "link": "https://github.com/flutter/flutter"},
    {"title": "React Native", "desc": "A framework for building native applications using React", "cat": "Mobile", "link": "https://github.com/facebook/react-native"},
    {"title": "Expo", "desc": "An open-source platform for making universal native apps for Android, iOS, and the web with JavaScript and React", "cat": "Mobile", "link": "https://github.com/expo/expo"},
    {"title": "Ionic", "desc": "A powerful cross-platform UI toolkit for building native-quality iOS, Android, and Progressive Web Apps with HTML, CSS, and JavaScript.", "cat": "Mobile", "link": "https://github.com/ionic-team/ionic-framework"},
    {"title": "Capacitor", "desc": "Build cross-platform Native Progressive Web Apps for iOS, Android, and the Web", "cat": "Mobile", "link": "https://github.com/ionic-team/capacitor"},
    {"title": "Tauri", "desc": "Build smaller, faster, and more secure desktop/mobile applications with a web frontend.", "cat": "Mobile", "link": "https://github.com/tauri-apps/tauri"},
    {"title": "Cordova", "desc": "Apache Cordova is a platform for building native mobile applications using HTML, CSS and JavaScript", "cat": "Mobile", "link": "https://github.com/apache/cordova-ios"},
    {"title": "NativeScript", "desc": "NativeScript empowers you to access native APIs from JavaScript directly", "cat": "Mobile", "link": "https://github.com/NativeScript/NativeScript"},
    {"title": "Kotlin", "desc": "The Kotlin Programming Language.", "cat": "Mobile", "link": "https://github.com/JetBrains/kotlin"},
    {"title": "Swift", "desc": "The Swift Programming Language", "cat": "Mobile", "link": "https://github.com/apple/swift"},
    {"title": "Alamofire", "desc": "Elegant HTTP Networking in Swift", "cat": "Mobile", "link": "https://github.com/Alamofire/Alamofire"},
    {"title": "Retrofit", "desc": "A type-safe HTTP client for Android and Java", "cat": "Mobile", "link": "https://github.com/square/retrofit"},
    {"title": "OkHttp", "desc": "Square’s meticulous HTTP client for the JVM, Android, and GraalVM.", "cat": "Mobile", "link": "https://github.com/square/okhttp"},
    {"title": "Glide", "desc": "An image loading and caching library for Android focused on smooth scrolling", "cat": "Mobile", "link": "https://github.com/bumptech/glide"},
    {"title": "Picasso", "desc": "A powerful image downloading and caching library for Android", "cat": "Mobile", "link": "https://github.com/square/picasso"},
    {"title": "Lottie (Android)", "desc": "Render After Effects animations natively on Android and iOS, Web, and React Native", "cat": "Mobile", "link": "https://github.com/airbnb/lottie-android"},
    {"title": "Lottie (iOS)", "desc": "An iOS library to natively render After Effects vector animations", "cat": "Mobile", "link": "https://github.com/airbnb/lottie-ios"},
    {"title": "RxJava", "desc": "RxJava – Reactive Extensions for the JVM", "cat": "Mobile", "link": "https://github.com/ReactiveX/RxJava"},
    {"title": "RxSwift", "desc": "Reactive Programming in Swift", "cat": "Mobile", "link": "https://github.com/ReactiveX/RxSwift"},
    {"title": "Realm", "desc": "Realm is a mobile database: a replacement for SQLite & Core Data", "cat": "Mobile", "link": "https://github.com/realm/realm-swift"},
    {"title": "Fastlane", "desc": "The easiest way to automate building and releasing your iOS and Android apps", "cat": "Mobile", "link": "https://github.com/fastlane/fastlane"},
    {"title": "Appium", "desc": "Cross-platform test automation framework for native, hybrid, and mobile web apps.", "cat": "Mobile", "link": "https://github.com/appium/appium"},
    {"title": "Detox", "desc": "Gray box end-to-end testing and automation framework for mobile apps", "cat": "Mobile", "link": "https://github.com/wix/Detox"},
    {"title": "Maestro", "desc": "The easiest way to automate UI testing for your mobile app.", "cat": "Mobile", "link": "https://github.com/mobile-dev-inc/maestro"},
    {"title": "Ignite", "desc": "The most popular React Native boilerplate.", "cat": "Mobile", "link": "https://github.com/infinitered/ignite"},
    {"title": "React Navigation", "desc": "Routing and navigation for your React Native apps", "cat": "Mobile", "link": "https://github.com/react-navigation/react-navigation"},
    {"title": "Reanimated", "desc": "React Native's Animated library reimplemented", "cat": "Mobile", "link": "https://github.com/software-mansion/react-native-reanimated"},
    {"title": "Flipper", "desc": "A desktop debugging platform for mobile developers.", "cat": "Mobile", "link": "https://github.com/facebook/flipper"},
    {"title": "Kingfisher", "desc": "A lightweight, pure-Swift library for downloading and caching images from the web.", "cat": "Mobile", "link": "https://github.com/onevcat/Kingfisher"},
    {"title": "SnapKit", "desc": "A Swift Autolayout DSL for iOS & OS X", "cat": "Mobile", "link": "https://github.com/SnapKit/SnapKit"},

    # DevOps (30)
    {"title": "Docker", "desc": "Docker - the open-source application container engine", "cat": "DevOps", "link": "https://github.com/docker/docker-ce"},
    {"title": "Kubernetes", "desc": "Production-Grade Container Scheduling and Management", "cat": "DevOps", "link": "https://github.com/kubernetes/kubernetes"},
    {"title": "Terraform", "desc": "Terraform enables you to safely and predictably create, change, and improve infrastructure.", "cat": "DevOps", "link": "https://github.com/hashicorp/terraform"},
    {"title": "Ansible", "desc": "Ansible is a radically simple IT automation platform", "cat": "DevOps", "link": "https://github.com/ansible/ansible"},
    {"title": "Helm", "desc": "The Kubernetes Package Manager", "cat": "DevOps", "link": "https://github.com/helm/helm"},
    {"title": "Prometheus", "desc": "The Prometheus monitoring system and time series database.", "cat": "DevOps", "link": "https://github.com/prometheus/prometheus"},
    {"title": "Grafana", "desc": "The open and composable observability and data visualization platform.", "cat": "DevOps", "link": "https://github.com/grafana/grafana"},
    {"title": "GitLab", "desc": "GitLab is an open source end-to-end software development platform", "cat": "DevOps", "link": "https://github.com/gitlabhq/gitlabhq"},
    {"title": "ArgoCD", "desc": "Declarative continuous deployment for Kubernetes.", "cat": "DevOps", "link": "https://github.com/argoproj/argo-cd"},
    {"title": "Jenkins", "desc": "Jenkins is the leading open source automation server", "cat": "DevOps", "link": "https://github.com/jenkinsci/jenkins"},
    {"title": "Vault", "desc": "A tool for secrets management, encryption as a service, and privileged access management", "cat": "DevOps", "link": "https://github.com/hashicorp/vault"},
    {"title": "Consul", "desc": "Consul is a distributed, highly available, and data center aware solution to connect and configure applications", "cat": "DevOps", "link": "https://github.com/hashicorp/consul"},
    {"title": "Nomad", "desc": "Nomad is an easy-to-use, flexible, and performant workload orchestrator", "cat": "DevOps", "link": "https://github.com/hashicorp/nomad"},
    {"title": "Istio", "desc": "Connect, secure, control, and observe services.", "cat": "DevOps", "link": "https://github.com/istio/istio"},
    {"title": "Linkerd", "desc": "Ultralight, security-first service mesh for Kubernetes", "cat": "DevOps", "link": "https://github.com/linkerd/linkerd2"},
    {"title": "Traefik", "desc": "The Cloud Native Application Proxy", "cat": "DevOps", "link": "https://github.com/traefik/traefik"},
    {"title": "Caddy", "desc": "Fast and extensible multi-platform HTTP/1-2-3 web server with automatic HTTPS", "cat": "DevOps", "link": "https://github.com/caddyserver/caddy"},
    {"title": "Nginx", "desc": "NGINX official repository", "cat": "DevOps", "link": "https://github.com/nginx/nginx"},
    {"title": "Elasticsearch", "desc": "Free and Open, Distributed, RESTful Search Engine", "cat": "DevOps", "link": "https://github.com/elastic/elasticsearch"},
    {"title": "Logstash", "desc": "Logstash - transport and process your logs, events, or other data", "cat": "DevOps", "link": "https://github.com/elastic/logstash"},
    {"title": "Kibana", "desc": "Your window into the Elastic Stack", "cat": "DevOps", "link": "https://github.com/elastic/kibana"},
    {"title": "Loki", "desc": "Like Prometheus, but for logs.", "cat": "DevOps", "link": "https://github.com/grafana/loki"},
    {"title": "Jaeger", "desc": "CNCF Jaeger, a Distributed Tracing Platform", "cat": "DevOps", "link": "https://github.com/jaegertracing/jaeger"},
    {"title": "OpenTelemetry", "desc": "OpenTelemetry observability framework", "cat": "DevOps", "link": "https://github.com/open-telemetry/opentelemetry-collector"},
    {"title": "Minikube", "desc": "Run Kubernetes locally", "cat": "DevOps", "link": "https://github.com/kubernetes/minikube"},
    {"title": "K3s", "desc": "Lightweight Kubernetes", "cat": "DevOps", "link": "https://github.com/k3s-io/k3s"},
    {"title": "Pulumi", "desc": "Pulumi - Infrastructure as Code in any programming language.", "cat": "DevOps", "link": "https://github.com/pulumi/pulumi"},
    {"title": "LocalStack", "desc": "A fully functional local AWS cloud stack.", "cat": "DevOps", "link": "https://github.com/localstack/localstack"},
    {"title": "Vagrant", "desc": "Vagrant is a tool for building and distributing development environments.", "cat": "DevOps", "link": "https://github.com/hashicorp/vagrant"},
    {"title": "Packer", "desc": "Packer is a tool for creating identical machine images for multiple platforms from a single source configuration.", "cat": "DevOps", "link": "https://github.com/hashicorp/packer"},

    # UI/UX & Others (20)
    {"title": "Figma Plugins", "desc": "Explore top Figma open-source plugins.", "cat": "UI/UX", "link": "https://github.com/topics/figma-plugin"},
    {"title": "Excalidraw", "desc": "Virtual whiteboard for sketching hand-drawn like diagrams", "cat": "UI/UX", "link": "https://github.com/excalidraw/excalidraw"},
    {"title": "Penpot", "desc": "Penpot - The Open-Source design & prototyping platform", "cat": "UI/UX", "link": "https://github.com/penpot/penpot"},
    {"title": "Feather Icons", "desc": "Simply beautiful open source icons", "cat": "UI/UX", "link": "https://github.com/feathericons/feather"},
    {"title": "FontAwesome", "desc": "The iconic SVG, font, and CSS toolkit", "cat": "UI/UX", "link": "https://github.com/FortAwesome/Font-Awesome"},
    {"title": "Lucide", "desc": "Beautiful & consistent icons", "cat": "UI/UX", "link": "https://github.com/lucide-icons/lucide"},
    {"title": "Heroicons", "desc": "A set of free MIT-licensed high-quality SVG icons for UI development.", "cat": "UI/UX", "link": "https://github.com/tailwindlabs/heroicons"},
    {"title": "Radix UI", "desc": "Primitives and themes for building react apps.", "cat": "UI/UX", "link": "https://github.com/radix-ui/primitives"},
    {"title": "Headless UI", "desc": "Completely unstyled, fully accessible UI components", "cat": "UI/UX", "link": "https://github.com/tailwindlabs/headlessui"},
    {"title": "Tailwind Components", "desc": "Free open source Tailwind CSS components.", "cat": "UI/UX", "link": "https://tailwindcomponents.com"},
    {"title": "Shadcn UI", "desc": "Beautifully designed components that you can copy and paste into your apps.", "cat": "UI/UX", "link": "https://github.com/shadcn-ui/ui"},
    {"title": "Mantine", "desc": "A fully featured React components library", "cat": "UI/UX", "link": "https://github.com/mantinedev/mantine"},
    {"title": "Chakra UI", "desc": "Simple, Modular & Accessible UI Components for your React Applications", "cat": "UI/UX", "link": "https://github.com/chakra-ui/chakra-ui"},
    {"title": "Design Resources", "desc": "A curated list of design and UI resources", "cat": "UI/UX", "link": "https://github.com/bradtraversy/design-resources-for-developers"},
    {"title": "Dribbble", "desc": "Discover the world’s top designers & creatives", "cat": "UI/UX", "link": "https://dribbble.com"},
    {"title": "Behance", "desc": "Showcase and discover creative work", "cat": "UI/UX", "link": "https://www.behance.net"},
    {"title": "Awwwards", "desc": "Website Awards - Best Web Design Trends", "cat": "UI/UX", "link": "https://www.awwwards.com"},
    {"title": "Color Hunt", "desc": "Color Palettes for Designers and Artists", "cat": "UI/UX", "link": "https://colorhunt.co"},
    {"title": "Coolors", "desc": "The super fast color palettes generator!", "cat": "UI/UX", "link": "https://coolors.co"},
    {"title": "Google Fonts", "desc": "Making the web more beautiful, fast, and open through great typography", "cat": "UI/UX", "link": "https://fonts.google.com"}
]

with open('atlas.html', 'r') as f:
    html = f.read()

# Find the existing resources array declaration
pattern = r'(const resources = \[.*?\];)'
match = re.search(pattern, html, re.DOTALL)

if not match:
    print("Could not find resources array")
    exit(1)

# Dump new array into JS format
js_array = "const resources = " + json.dumps(new_resources, indent=2) + ";"

new_html = html.replace(match.group(1), js_array)

with open('atlas.html', 'w') as f:
    f.write(new_html)

print(f"✅ Injected {len(new_resources)} repositories into atlas.html")
